.kitchen.cloud.yml, Berksfile, metadata.rb, recipes/master.rb, test/integration/master/serverspec/master_spec.rb
Migrating these from the jenkins_master role.
=> Adds default attributes for jenkins:master.

recipes/master.rb
@osuosl-cookbooks/chefs please review
=> Freeze jenkins to current version

templates/default/bump_environments.rb.erb
This reverts commit f7318e2de4e691c1f85fc35a61004a48b5e886b9.
=> Revert "Make sure to update master branch before creating branches"

recipes/osl_cookbook_uploader.rb
https://github.com/osuosl/chef-repo/pull/377
=> Remove dev environment from default envs

libraries/github.rb
This doesn't need to be installed for every repo!
@osuosl-cookbooks/chefs please review
=> Remove extra gem install of octokit

.gitignore, .rspec, Rakefile, chefignore, recipes/chef_ci_cookbook_template.rb, spec/chef_ci_cookbook_template_spec.rb, spec/spec_helper.rb, test/integration/chef_ci_cookbook_template/serverspec/chef_ci_cookbook_template_spec.rb
=> Set chefdk version on jenkins to 0.14.25

templates/default/github_pr_comment_trigger.rb.erb
=> Use knife cookbook upload instead of berkshelf

.kitchen.yml, Rakefile, attributes/default.rb, recipes/master.rb, spec/unit/recipes/master_spec.rb, test/integration/master/serverspec/master_spec.rb
This is useful for adding ssh private keys for users.
=> Add ssh private key credential support

recipes/bumpzone.rb, recipes/cookbook_uploader.rb, recipes/github_comment.rb, recipes/master.rb, spec/unit/recipes/cookbook_uploader_spec.rb, spec/unit/recipes/github_comment_spec.rb, spec/unit/recipes/master_spec.rb
This matches a working config in production. Without this we run into
downgrading problems. I will work on a separate PR to unify plugin installation
in a saner fashion so we don't have the versions all over the place.
=> Update pinned versions of various jenkins plugins

templates/default/bumpzone.config.xml.erb, templates/default/checkzone.config.xml.erb
Otherwise this tries to run on any node and that's not intended.
=> Set canRoam to false so assigned node works properly

files/default/bin/deploy.sh
This is stage 5 of `!taste` and stage 1 of `!deploy`
=> Add deploy.sh for bento pipeline

README.md
Accidentally merged the PR closing fix instead of bumping. This pr is just to do a bump, and contains a trivial change to README
=> trivial change to re-open PR

.kitchen.yml, userdata.txt
Also allow connections from github for better testing
=> Bring both public & vlan42 network interfaces

attributes/plugins.rb, spec/unit/recipes/plugins_spec.rb, test/integration/plugins/serverspec/plugins_spec.rb
makes it easier for the packer-pipeline to serialize and deserialize data like results and payload.
https://github.com/jenkinsci/pipeline-utility-steps-plugin/blob/master/docs/STEPS.md
=> plugin with inbuilt capabilities of readJSON & writeJSON

attributes/packer_pipeline.rb
=> Bump openstack_taster to 1.0.2

recipes/packer_pipeline_node.rb, spec/unit/recipes/packer_pipeline_node_spec.rb, test/integration/packer_pipeline_node/serverspec/packer_pipeline_node_spec.rb
=> Install openstackclient using base::openstackclient

recipes/powerci.rb, spec/unit/recipes/powerci_spec.rb, test/integration/powerci/serverspec/powerci_spec.rb
This installs the sge-cloud-plugin directly from the URL since it's not
searchable in the plugin database for some reason.
=> Install SGE jenkins plugin on powerci

attributes/plugins.rb, recipes/powerci.rb, spec/unit/recipes/plugins_spec.rb, spec/unit/recipes/powerci_spec.rb, test/integration/plugins/serverspec/plugins_spec.rb, test/integration/powerci/serverspec/powerci_spec.rb
This also included updating/adding a few other dependant plugins to get this
working properly.
=> Update subversion and git plugins for security patches

libraries/docker.rb, spec/unit/recipes/ibmz_ci_spec.rb, spec/unit/recipes/powerci_spec.rb, test/integration/nodes/localhost.json
Otherwise Groovy complains and breaks.
=> Translate characters on hostnames which contain - to _ for function names

.kitchen.yml, attributes/site_pr_builder.rb, spec/unit/recipes/site_pr_builder_spec.rb, test/integration/site_pr_builder/serverspec/site_pr_builder_spec.rb
This was made to resolve 29982[1]. This requires the docs to be migrated to web2.
[1] https://support.osuosl.org/Ticket/Display.html?id=29982
=> Add jenkins job for building docs PRs

Rakefile, recipes/master.rb, spec/unit/recipes/master_spec.rb, test/integration/helpers/serverspec/spec_helper.rb
=> Update  to jenkins-2.107.3

recipes/powerci.rb, spec/unit/recipes/powerci_spec.rb, test/integration/powerci/serverspec/powerci_spec.rb
This includes two hosts with GPU's now!
=> Switch to using docker_gpu queue on SGE for powerci

files/default/bin/packer_pipeline.rb, files/default/lib/packer_pipeline.rb, spec/webhooks/packer_pipeline_spec.rb
Create a new CLI option which only does the deploy action (merge and delete
branch). Also include the PR commit state which will be used by Jenkinsfile.
=> Refactor !deploy yet again

attributes/plugins.rb, recipes/ibmz_ci.rb, recipes/master.rb, recipes/powerci.rb, spec/unit/recipes/ibmz_ci_spec.rb, spec/unit/recipes/master_spec.rb, spec/unit/recipes/plugins_spec.rb, spec/unit/recipes/powerci_spec.rb, test/integration/helpers/serverspec/spec_helper.rb, test/integration/ibmz_ci/serverspec/ibmz_ci_spec.rb, test/integration/plugins/serverspec/plugins_spec.rb, test/integration/powerci/serverspec/powerci_spec.rb
This provides the following:
- Bump to jenkins-2.138.2
- Update various plugins for security issues
- Bump ssh-slaves to 1.28.1
See individual commits for more information.
=> Various Updates

libraries/docker.rb, spec/unit/recipes/ibmz_ci_spec.rb, spec/unit/recipes/powerci_spec.rb, test/integration/ibmz_ci/serverspec/ibmz_ci_spec.rb, test/integration/powerci/serverspec/powerci_spec.rb
=> Add privileged docker labels for powerci/ibmz-ci

attributes/plugins.rb, recipes/ibmz_ci.rb, recipes/master.rb, recipes/powerci.rb, spec/unit/recipes/ibmz_ci_spec.rb, spec/unit/recipes/master_spec.rb, spec/unit/recipes/plugins_spec.rb, spec/unit/recipes/powerci_spec.rb, spec/webhooks/github_comment_spec.rb, test/integration/helpers/serverspec/spec_helper.rb, test/integration/ibmz_ci/serverspec/ibmz_ci_spec.rb, test/integration/plugins/serverspec/plugins_spec.rb, test/integration/powerci/serverspec/powerci_spec.rb
- Update various plugins which have security issues
- Add label-linked-jobs (and its dependencies) to powerci and ibmz
=> Bump to jenkins-2.150.2

.kitchen.yml, recipes/jenkins1.rb
This should not be merged until osuosl/chef-repo#1987 has been merged.
=> Add openstack_pike environment to default bump

recipes/master.rb, test/integration/data_bags/osl_jenkins/jenkins1.json
We switched to using the http protocol from remoting so this needs to be
updated.
=> Use username/password for cli executor instead of ssh key

recipes/ibmz_ci.rb, recipes/powerci.rb, spec/unit/recipes/ibmz_ci_spec.rb, spec/unit/recipes/powerci_spec.rb
Both converged with no dependency issues reported by Jenkins.
=> Add plugins to PowerCI and IBMZ

kitchen.yml, recipes/haproxy.rb, test/integration/haproxy/inspec/haproxy_spec.rb
=> Disable DES-CBC3-SHA cipher (CVE-2016-2183)

templates/default/cookbook-uploader.config.xml.erb, templates/default/environment-bumper.config.xml.erb
=> Add support for 'main' branches instead of 'master'

kitchen.yml, recipes/jenkins1.rb
=> Remove openstack_stein from default environments

recipes/bumpzone.rb, recipes/cookbook_uploader.rb, recipes/ibmz_ci.rb, recipes/powerci.rb, spec/unit/recipes/bumpzone_spec.rb, spec/unit/recipes/cookbook_uploader_spec.rb, spec/unit/recipes/ibmz_ci_spec.rb, spec/unit/recipes/powerci_spec.rb
This will replace _all_ credentials including user added ones. Let's just not
manage this for now.
=> Remove credential setup with JCASC

files/jobs/github_comment.groovy
=> Set label for github_comment job

.rubocop.yml, libraries/helpers.rb, metadata.rb, recipes/default.rb, resources/install.rb, spec/unit/recipes/controller_spec.rb, spec/unit/recipes/default_spec.rb, test/integration/controller/controls/controller_spec.rb, test/integration/default/controls/default_spec.rb
Using latest pulled in java 22 which Jenkins doesn't quite support yet.
=> Switch to java 21 instead of using latest

kitchen.dokken.yml, kitchen.openstack.yml, kitchen.yml
All tests green for all drivers, except for
* `powerci`
* `ibmz-ci`
Both have errors that are consistent across all drivers.
=> Test Kitchen Config Refactor

templates/ibmz-ci.yml.erb, templates/powerci.yml.erb
This should hopefully resolve some issues we're seeing in:
https://support.osuosl.org/Ticket/Display.html?id=33413
=> Sort docker hosts by fqdn

libraries/helpers.rb
=> Additional Github plugins required for Jenkinsfile deployments

Berksfile, attributes/powerci.rb, spec/unit/recipes/powerci_spec.rb, test/integration/powerci/controls/powerci_spec.rb
Remove unused and add newer platforms. Also switch to using private supermarket
in Berksfile.
=> Update powerci images

templates/default.yml.erb
This is causing issues starting Jenkins
=> Remove deprecated myViewsTabBar setting in config
