- .kitchen.cloud.yml
- Berksfile
- README.md
- metadata.rb
- recipes/chef_ci.rb
- recipes/chef_ci_cookbook_template.rb
- test/integration/chef_ci_cookbook_template/serverspec/chef_ci_cookbook_template_spec.rb
Installs:
* foodcritic
* rubocop
using the `chef-dk` cookbook. This is for the `chef-ci-cookbook-template` job.
> Add Chef CI Cookbook Template Dependencies

- test/integration/chef_ci_cookbook_template/serverspec/chef_ci_cookbook_template_spec.rb
Fix the one issue raised by rubocop:
-  ``W: Ambiguous regexp literal. Parenthesize the method arguments if it's surely a regexp literal ...``
> Rubocop Fixes

- recipes/default.rb
- test/integration/default/serverspec/default_spec.rb
The project has stated their desire to move to Java 8 in late
2016. We might as well use the latest version.
> Install jdk 8 for jenkins client.

- recipes/master.rb
The logic in
https://github.com/chef-cookbooks/jenkins/blob/master/attributes/default.rb#L45-L53
is causing chef to restart runs every time.
> Manually set jenkins java path to stop restarts during chef runs

- Berksfile
- libraries/github.rb
- metadata.rb
- recipes/cookbook_uploader.rb
This uses versions as they are currently installed in prod. This should work around the issue we're having with chef runs on jenkins1. Tests will come in a later PR as its ... complicated.
> Lock version per plugin

- .kitchen.yml
- metadata.rb
- recipes/jenkins1.rb
- recipes/master.rb
- spec/spec_helper.rb
- spec/unit/recipes/jenkins1_spec.rb
- test/integration/helpers/serverspec/spec_helper.rb
- test/integration/jenkins1/serverspec/jenkins1_spec.rb
- test/smoke/default/jenkins1.rb
This moves all of the logic we have currently in roles for jenkins1.osuosl.org
into it's own recipe to test it easier. This also moves specific changes for
jenkins1 out of the master recipe. The master recipe was pulling in things it
shouldn't be such as chefdk due to the inclusion of the cookbook uploader
recipe. This simplifies it for easier testing of other new recipes down the
road.
In addition, I also made these changes and/or fixes:
- Updated the repo to use to test to test-cookbook (lanparty was removed)
- Created a github security group on OpenStack so that we don't leave these
instance wide open to the internet
- Added very basic unit tests for the jenkins1 recipe
- Created a shared ServerSpec test for testing basic jenkins functionality
- Include build-essential for CentOS 6 due …
> Create recipe for jenkins1.o.o that replicates roles

- .kitchen.yml
- attributes/default.rb
- recipes/cookbook_uploader.rb
- spec/spec_helper.rb
- spec/unit/recipes/cookbook_uploader_spec.rb
I neglected to notice that we had switched away from using the password to using
an API token in 5a6b4e051dcfd8e6684ae49a3020cdeca15cdf4f. This resolves that
issue.
> Switch to using Jenkins API token instead of password

- recipes/jenkins1.rb
Removing the old openstack environments as we don't want to bump anything there
anymore and replacing them with the openstack_mitaka. Adding testing and
phase_out_nginx since those should be safe to bump (usually).
> Update list of default environments the bump ~ command uses

- files/default/lib/bumpzone.rb
- files/default/lib/github_comment.rb
- libraries/github.rb
- recipes/bumpzone.rb
- recipes/cookbook_uploader.rb
- recipes/github_comment.rb
- spec/unit/recipes/cookbook_uploader_spec.rb
- templates/default/bump_environments.rb.erb
- templates/default/github_pr_comment_trigger.rb.erb
This enables caching for Github API calls based on upstream documentation [1].
This should improve some of the lookups we do and probably also minimize the
random errors we get likely due to API limiting from github.
[1] https://github.com/octokit/octokit.rb#caching
> Enable Octokit API caching

- templates/default/bumpzone.config.xml.erb
- templates/default/checkzone.config.xml.erb
Without this, it doesn't work in production properly.
> Assign master node for bumpzone/checkzone jobs

- .kitchen.yml
- attributes/plugins.rb
- recipes/bumpzone.rb
- recipes/cookbook_uploader.rb
- recipes/github_comment.rb
- recipes/master.rb
- recipes/plugins.rb
- spec/unit/recipes/bumpzone_spec.rb
- spec/unit/recipes/cookbook_uploader_spec.rb
- spec/unit/recipes/github_comment_spec.rb
- spec/unit/recipes/master_spec.rb
- spec/unit/recipes/plugins_spec.rb
- test/integration/plugins/serverspec/plugins_spec.rb
This pulls in all plugin installation to one place. It also replicates the
plugins that are installed on the production jenkins master. To work around the
issues described in chef-cookbooks/jenkins#534, we default to install without
plugin dependencies and directly install the exact version of every plugin we
need.
In addition:
- Remove extraneous attributes from test-kitchen
- Update git-client due to security issue
> Install plugins all from one recipe

- recipes/site_pr_builder.rb
Looks like the 'htdocs' component of the build path got lost somewhere, resulting in the site being in the wrong place.
> add missing 'htdocs'

- .kitchen.yml
- recipes/powerci.rb
- spec/unit/recipes/powerci_spec.rb
- test/integration/powerci/serverspec/powerci_spec.rb
Initial work for power-ci.o.o. Installs Jenkins, Jenkins plugins, and haproxy. 
The list of Jenkins plugins is taken from https://power-ci.osuosl.org/jenkins/
Because of a delay when Jenkins is restarting, kitchen test will most likely fail. Running kitchen verify again after the failure will usually work.
> Add recipe for power-ci

- attributes/site_pr_builder.rb
- spec/unit/recipes/site_pr_builder_spec.rb
- test/integration/site_pr_builder/serverspec/site_pr_builder_spec.rb
Docs build is broken, most likely due to docs being a private repo. This PR removes the docs builder job from chef until we figure out how to fix.
> remove docs builder until fixed

- templates/default/site_pr_builder_config.xml.erb
Turns out the pr builder job has an advanced option to delete failed PRs, defaulting to 'true' this should prevent the builder jobs from closing prs.
> don't close prs even if they break

- recipes/packer_pipeline_node.rb
- spec/spec_helper.rb
- spec/unit/recipes/packer_pipeline_node.rb
- test/integration/data_bags/osl_jenkins/jenkins1.json
- test/integration/packer_pipeline_node/serverspec/packer_pipeline_node_spec.rb
openstack_taster requires the private key, whose public key part is put on the openstack clusters, to be accessible locally so as to be able to SSH into the instances.
@DesertBeagle had put the key in data bags long back, but I hadn't made them available on the nodes.
This should take care of that.
> setup keys to use with openstack taster

- .kitchen.yml
- recipes/packer_pipeline_node.rb
- spec/unit/recipes/packer_pipeline_node.rb
This would also require installing the dependencies at compile_time
since chef installs chef_gem at compile time too.
It seems until now Chef was simply falling back to installing openstack_taster
by default as a chef_gem when a system ruby was not available.
This didn't hit our radar until we saw a machine which had both rubies.
> install openstack_taster as a chef_gem explicitly

- files/default/lib/packer_pipeline.rb
~Aims to~ Fixes the bug #94 in alliance with the latest commits on https://github.com/osuosl/packer-templates/pull/26
Since the `packer-templates` repo was not checked out on master, our payload processor never looked at them and always returned only the templates which were present in the PR and *not* the templates which were also affected by the changes in the PR (it's original purpose)
This makes it look at the right dir and along with the other changes to Jenkinsfile ensures that the find the right affected templates.
A latest result of this can be seen by comparing current [1] and old [2] CI packer-pipeline jobs output
[1] https://jenkins.osuosl.org/job/packer_pipeline/91/console
[2] https://jenkins.osuosl.org/job/packer_pipeline/60/console
> Fix for #94

- metadata.rb
- recipes/master.rb
- spec/unit/recipes/master_spec.rb
- test/integration/helpers/serverspec/spec_helper.rb
Other fixes included:
- Use yum-version-lock to ensure we don't accidentally upgrade jenkins
Something to keep in mind is that this is the first release which requires Java 8 to run according to the [Changelog](https://jenkins.io/changelog-stable/). I checked a while back and I'm pretty sure all of our clients are using Java 8 but it wouldn't hurt to double check.
> Update to Jenkins 2.60.2

- recipes/powerci.rb
- spec/unit/recipes/powerci_spec.rb
- test/integration/data_bags/osl_jenkins/powerci.json
- test/integration/powerci/serverspec/powerci_spec.rb
This adds a jenkins_script that configures a docker cloud. It also avoids the problem of creating duplicate entries when run multiple time which was a problem I had with the original Ansible setup. 
This Works:tm: but I wasn't sure if we wanted to pull out specific settings and make them attributes, or go about this some other way. Not sure if this something that we want to be able to reuse and should be put in another recipe and then just set the attributes in the powerci recipe.
Thoughts?
> Add jenkins_scripts for Docker cloud, OpenStack Cloud, GitHub Oauth

- recipes/packer_pipeline_node.rb
- spec/unit/recipes/packer_pipeline_node.rb
- test/integration/packer_pipeline_node/serverspec/packer_pipeline_node_spec.rb
This installs the [python-openstackclient](https://pypi.python.org/pypi/python-openstackclient) package using `poise-python`, _if_ it is not already installed.
Hence it would require us to `scl-enable` python everytime we want to use it.
> openstack client for pipeline nodes

- templates/default/packer_pipeline.config.xml.erb
We had it pointed to samarendra/pipeline_script branch which is now
merged into master with https://github.com/osuosl/packer-templates/pull/26
> Use the Jenkinsfile from packer-templates/master branch

- recipes/packer_pipeline_node.rb
- spec/unit/recipes/packer_pipeline_node.rb
- test/integration/packer_pipeline_node/serverspec/packer_pipeline_node_spec.rb
This is required to provide `berks` and other utilities which are used in building packer images which require chef provisioning like the mitaka-aio and mitaka-identity images
> Setup chefdk on packer-pipeline nodes

- .rubocop.yml
- files/default/bin/packer_pipeline.rb
- files/default/lib/packer_pipeline.rb
- spec/fixtures/final_results_multiple_templates.json
- spec/fixtures/final_results_single_template.json
- spec/webhooks/packer_pipeline_spec.rb
This also changes the original packer_pipeline ruby binary to accept a JSON file for either processing the GitHub payload or to set the status on the GitHub commit by processing the final results array created by the pipeline.
The status will be set as demonstrated on osuosl/packer-templates#29, (ignoring the template1 and template2)
> Set status on PR for packer-templates repo

- templates/default/packer_pipeline.config.xml.erb
This will probably spare the master from being overwhelmed by the pipeline.
This will:
* Allow only 2 builds to be executed in an hour on the packer_pipeline. The packer pipeline's architecture is such that that the master waits on the nodes to complete and return output thus eating up multiple "run slots" on the master. Rate-limiting it to only 2 builds in an hour should mean we are leaving other run slots for other jobs on the master like the linter.
* Set a quiet period of 10 minutes. 
Jenkins puts it better
``
For example, if your builds take a long time to execute, you may want to prevent multiple source control commits that are made at approximately the same time from triggering multiple builds. Enabling the quiet period would prevent a build from being started as soon as Jenkins …
> Ratelimit and add a quiet period to packer_pipeline.

- files/default/lib/packer_pipeline.rb
- spec/webhooks/packer_pipeline_spec.rb
Thus 'scripts/centos/cleanup.sh' and 'scripts/ubuntu/cleanup.sh' will now be differentiated when looking inside templates' shell provisioners.
This fixes the library as well as the tests.
Discovered when trying to test the essentiality of various ubuntu scripts in osuosl/packer-templates#39
> Dependent templates are now searched for by using full path.

- recipes/jenkins1.rb
As of https://github.com/osuosl/chef-repo/commit/9e8397df32bab644fcceb5a167fa7a96f3269e13, the testing environment no longer exists in chef-repo, which means trying to run a bump command with the default env's fails, such as [here](https://github.com/osuosl-cookbooks/proj-phpbb/pull/204).
> Remove testing env from default env

- attributes/plugins.rb
- recipes/powerci.rb
- spec/unit/recipes/plugins_spec.rb
- spec/unit/recipes/powerci_spec.rb
- test/integration/plugins/serverspec/plugins_spec.rb
- test/integration/powerci/serverspec/powerci_spec.rb
This updates github-api to version 1.90 this resolves this issue [1] that we're
currently hitting with our Jenkins servers.
[1] https://issues.jenkins-ci.org/browse/JENKINS-47601
> Bump github-api to 1.90 to work around issue with their API

- templates/default/packer_pipeline.config.xml.erb
There's no need to set the quiet period for this job. In addition, let's
increase the amount of jobs we can run from 2 per hour to 4 per hour. I think
this is a more sensible configuration for now.
> Adjust timeouts for packer jobs

- templates/default/packer_pipeline.config.xml.erb
I don't think this is really needed anymore and it's causing more problems than
helping.
> Disable throttle for packer builds

- attributes/plugins.rb
- recipes/master.rb
- recipes/powerci.rb
- spec/unit/recipes/master_spec.rb
- spec/unit/recipes/plugins_spec.rb
- spec/unit/recipes/powerci_spec.rb
- test/integration/helpers/serverspec/spec_helper.rb
- test/integration/plugins/serverspec/plugins_spec.rb
- test/integration/powerci/serverspec/powerci_spec.rb
Also do the following security updates on the plugins:
- credentials-binding
- junit
- scm-api
- workflow-support
> Bump to jenkins-2.89.4

- attributes/plugins.rb
- recipes/ibmz_ci.rb
- recipes/master.rb
- recipes/powerci.rb
- spec/unit/recipes/ibmz_ci_spec.rb
- spec/unit/recipes/master_spec.rb
- spec/unit/recipes/plugins_spec.rb
- spec/unit/recipes/powerci_spec.rb
- test/integration/helpers/serverspec/spec_helper.rb
- test/integration/ibmz_ci/serverspec/ibmz_ci_spec.rb
- test/integration/plugins/serverspec/plugins_spec.rb
- test/integration/powerci/serverspec/powerci_spec.rb
This also provides updates to the following plugins:
- display-url-api
- ghprb
- github
- mailer
- matrix-project
In addition, this pulls in some updates on powerci and ibmz-ci and also bringing
them into sync somewhat.
> Update to jenkins-2.107.2

- libraries/docker.rb
This automatically attaches a 'ccache' volume which is created in osl-docker for
each environment.
> Add ccache volume to all docker instances for POWER/IBM-Z CI

- recipes/site_pr_builder.rb
The https site is required somewhere in the build process, so this will revert the change that made it use SSH until we find a better way to pull from private repos.
> Revert "Use SSH instead of HTTPS for pulling github repos"

- attributes/packer_pipeline.rb
- recipes/packer_pipeline_node.rb
- spec/unit/recipes/packer_pipeline_node_spec.rb
- test/integration/helpers/serverspec/spec_helper.rb
Since we control when new releases of openstack_taster, we don't need to lock
the version in the cookbook. This removes the requirement of bumping this
cookbook on every new release. It also ensures that it always uses the latest
version which it currently does even if you bump the version.
Also move jenkins checking code into the shared_examples block since that was breaking tests.
> Always upgrade openstack_taster

- .rubocop.yml
- files/default/lib/packer_pipeline.rb
- spec/fixtures/final_results_single_template_deploy.json
- spec/fixtures/final_results_single_template_deploy_failed.json
- spec/webhooks/packer_pipeline_spec.rb
This greatly expands what !deploy does in the back end and provides the
following new enhancements:
- Correctly find the PR number if this is an issue vs a pr event
- Add a new field in the payload called event_type which states that it's either
an issue or a pull_request
- If GIT_COMMIT doesn't exist, find the latest commit on the PR and use that
comment
- If all states pass, the PR hasn't been merged or is mergable, go ahead and do
the following:
- Merge the pull request
- Delete the branch
- If the PR has already been merged or isn't mergable, stop and post a comment
on the PR stating that it can't be merged for those reasons
> Add more enhancements to !deploy functionality

- recipes/powerci.rb
- spec/unit/recipes/powerci_spec.rb
We're not even currently using the OpenStack cloud instance (yet) and I'm
seeing errors such as the following in the logs:
```
SEVERE: A thread (OpenStack slave cleanup thread/5527) died unexpectedly due to an uncaught exception, this may leave y
our Jenkins in a bad way and is usually indicative of a bug in the code.
ConnectionException{status=0}
at org.openstack4j.connectors.httpclient.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:60)
at org.openstack4j.connectors.httpclient.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:32)
at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV2(OSAuthenticator.java:122)
at …
```
> Disable OpenStack cloud in powerci due to potential issues

- libraries/sge.rb
- recipes/powerci.rb
- spec/unit/recipes/powerci_spec.rb
- test/integration/powerci/serverspec/powerci_spec.rb
We've run into an issue where one of our users is having problems running jobs
on two different machines in the same label [1]. This is due to the fact that
these two servers have different CUDA drivers installed. One that supports 9.2
and another that doesn't. To work around this issue we're going to create two
new labels which point to the specific hosts which should work.
I needed to refactor the code for SGE a bit to deal with adding more than one
SGE cloud, but other than that, it's the same logic as before.
[1] https://support.osuosl.org/Ticket/Display.html?id=30202
> Create new GPU labels for CUDA 9.1 and 9.2

- libraries/docker.rb
- spec/spec_helper.rb
- test/integration/powerci/serverspec/powerci_spec.rb
This is to work around a leak issue we're running into on the powerci jenkins.
It seems to be related to this [1] and has a suggested workaround which is this.
We've already updated the ssh-agents plugin to the version higher than they
suggest.
[1] https://support.cloudbees.com/hc/en-us/articles/115002327291-SSH-Agents-leak-Computer-threadPoolForRemoting-threads
> Set SSH connection timeout to 600 seconds

- recipes/powerci.rb
- spec/unit/recipes/powerci_spec.rb
- test/integration/powerci/serverspec/powerci_spec.rb
CGRB is going to be taking the machine this label uses out of rotation so that
we can use it as an OpenStack GPU node. There are no current jobs using this
label so it should be safe to remove.
> Remove docker-gpu-cuda91 label

- files/default/lib/packer_pipeline.rb
- spec/fixtures/centos-7-x86_64-newton-aio-openstack.json
This ensures that we don't run into an issue where scripts returns nil when
using an inline script. This was happening with this job [1].
[1] https://jenkins.osuosl.org/job/packer_pipeline/579/console
> Fix bug when templates use an inline script

- attributes/ibmz_ci.rb
- attributes/powerci.rb
- spec/unit/recipes/ibmz_ci_spec.rb
- spec/unit/recipes/powerci_spec.rb
- test/integration/ibmz_ci/serverspec/ibmz_ci_spec.rb
- test/integration/powerci/serverspec/powerci_spec.rb
In addition:
- Include the buster and unstable tags for the Debian s390x image
- Update to Fedora 29 and remove anything older than 28
- Include all of the base CUDA images between 9.0-9.2 which seemed to have been
accidentally left off
This also resolves RT 30455 [1]
[1] https://support.osuosl.org/Ticket/Display.html?id=30455
> Add CUDA 10.0 images

- .kitchen.yml
- recipes/jenkins1.rb
These are no longer being used and are being removed in osuosl/chef-repo#1867.
> Remove gwm and phase_out_nginx environments

- attributes/plugins.rb
- recipes/ibmz_ci.rb
- recipes/plugins.rb
- recipes/powerci.rb
- spec/unit/recipes/plugins_spec.rb
- test/integration/plugins/serverspec/plugins_spec.rb
This simplifies dealing with plugins between our standard deployment vs. powerci
and ibmz-ci. This also allows us to ensure we have the same (or nearly the same)
versions of the plugins installed globally. I've been meaning to make this
change for ages!
In addition, updated ircbot to 2.30.
> Refactor plugins attribute to use hash instead of array

- recipes/ibmz_ci.rb
- recipes/powerci.rb
- spec/unit/recipes/ibmz_ci_spec.rb
- spec/unit/recipes/powerci_spec.rb
- test/integration/ibmz_ci/serverspec/ibmz_ci_spec.rb
- test/integration/powerci/serverspec/powerci_spec.rb
This will allow projects to deploy their jobs using docker using any container
image they need or want.
> Add docker-custom-build-environment plugin on powerci and ibmz-ci instances

- recipes/default.rb
- spec/unit/recipes/default_spec.rb
- test/integration/default/serverspec/default_spec.rb
This is needed for utilizing the docker-custom-build-environment plugin. We need
to have a known static UID in containers on all hosts acting as a jenkins node.
I will be deploying a one-time manual fix on each current node as this doesn't
fix any current running processes or change the gid for the home directory
correctly from the current setup.
> Set alfred gid/uid to something static

- recipes/master.rb
We never added it in the metadata.rb so this is the only change that's needed.
> Remove reliance on chef-sugar since we don't need it here anyway

- recipes/packer_pipeline_node.rb
- spec/unit/recipes/packer_pipeline_node_spec.rb
- test/integration/packer_pipeline_node/inspec/packer_pipeline_node_spec.rb
For preparing for Chef 14, we need to update the version of InSpec we depend on.
We'll be making that change in 2.0 of openstack_taster so let's ensure the
current environment doesn't accidentally pull in the newer version once it's
pushed.
NOTE: The automatic tests will likely fail since this cookbook hasn't been updated to 14 yet, however this is a pre-req for it.
> Ensure we only install < 2.0 for openstack_taster

- attributes/cookbook_uploader.rb
- libraries/default.rb
By default, we're using the FQDN for setting the hostname used in Github
webhooks. This becomes a problem when deploying more than one OSL Jenkins server
for a migration. It makes more sense to just point to the hostname we actually
use for our Jenkins instance.
This should make it easier to do major server platform upgrades on our primary
Jenkins server.
> Use vhost hostname for jenkins server webhooks

- metadata.rb
Some breaking changes in 8.0 that require Chef 15.
> Pin java cookbook to < 8.0

- recipes/bumpzone.rb
- recipes/chef_backup.rb
- recipes/chef_ci_cookbook_template.rb
- recipes/cookbook_uploader.rb
- recipes/default.rb
- recipes/ftp.rb
- recipes/github_comment.rb
- recipes/haproxy.rb
- recipes/ibmz_ci.rb
- recipes/jenkins1.rb
- recipes/master.rb
- recipes/packer_pipeline_master.rb
- recipes/packer_pipeline_node.rb
- recipes/plugins.rb
- recipes/powerci.rb
- recipes/site_pr_builder.rb
- spec/unit/recipes/packer_pipeline_node_spec.rb
- test/integration/packer_pipeline_node/inspec/packer_pipeline_node_spec.rb
We are not currently using it and I'm not planning on using it in the future however I'm not ready to completely remove the code here just in case.
This should fix chef runs that are currently failing due to this.
In addition, cookstyle fixes.
> Temporarily disable installation of the openstack_taster gem

- metadata.rb
No other changes needed to use the latest version.
> Bump yum-versionlock cookbook version

- metadata.rb
6.x and above removes support for data bags natively and we're not ready for that yet.
> Put a ceiling on users cookbook

- templates/default/site_pr_builder_config.xml.erb
This ensures that it uses the virtual environment so that it can use the doc8 binary.
> Move linting command to script

- metadata.rb
Also avoid java-12 cookbook until they fix the issues.
> Bump to java-11.2.2

- resources/install.rb
- spec/unit/recipes/controller_spec.rb
This will allow Jenkins to start fully and not exceed Chef's 10 minute timeout.
> Set TimeoutStartSec to just under 10 minutes

- attributes/cookbook_uploader.rb
- libraries/github.rb
- recipes/cookbook_uploader.rb
- spec/unit/recipes/cookbook_uploader_spec.rb
- spec/unit/recipes/jenkins1_spec.rb
- test/integration/cookbook-uploader/controls/cookbook_uploader_spec.rb
This also adds a check to only create jobs if the repo is not archived.
> Delete JASC configs for archived repositories

- templates/default.yml.erb
This fixes the following issue:
Configuration as Code obsolete file format:
'diskSpaceMonitor' is obsolete, please use 'diskSpace'
https://support.osuosl.org/Ticket/Display.html?id=33413
> Rename diskSpaceMonitor to diskSpace

- kitchen.dokken.yml
- kitchen.yml
- recipes/ibmz_ci.rb
- recipes/powerci.rb
- spec/unit/recipes/ibmz_ci_spec.rb
- spec/unit/recipes/powerci_spec.rb
- templates/default.yml.erb
- test/integration/ibmz_ci/controls/ibmz_ci_spec.rb
- test/integration/powerci/controls/powerci_spec.rb
This was requested on this ticket [1].
In addition:
- Update default Chef version to 18
- Remove mavenModuleSet from default template as it breaks on new installs
[1] https://support.osuosl.org/Ticket/Display.html?id=33647#txn-738496
> Add basic-branch-build-strategies plugin on powerci/ibmz-ci

- recipes/bumpzone.rb
- recipes/chef_backup.rb
- recipes/cookbook_uploader.rb
- recipes/default.rb
- recipes/github_comment.rb
- recipes/ibmz_ci.rb
- recipes/jenkins1.rb
- recipes/powerci.rb
- templates/default.yml.erb
This is now deprecated and causes issues with newer versions of Jenkins.
> Remove agentProtocols from jasc config

- templates/default/github_pr_comment_trigger.rb.erb
Wasn't able to successfully test the `cookbook-uploaded` suite, as it failed to list the webhooks for `osuosl-cookbooks/test-cookbook`. I did test the new commands, personally, with success.
Will need help with looking into logging the Jenkins account into the supermarket before we push this to prod.
> Add supermarket share to cookbook-uploader script
